ROWS = 15
COLS = 15
TILE_SIZE = 32
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 15

#enemy constants
SPAWN_COOLDOWN = 385

#turret constants
TURRET_LEVELS = 4
RAPID_LEVELS = 1
BUY_COST = 150
UPGRADE_COST = 100
KILL_REWARD = 5
LEVEL_COMPLETE_REWARD = 200
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
DAMAGE = 5

RAPID_BUY_COST = 80
RAPID_DAMAGE = 2
